languages:
  JavaScript: true
  PHP: true
engines:
  phpmd:
    enabled: true
    checks:
      CleanCode/ElseExpression:
        enabled: false
exclude_paths:
- "view/base/web/js/tablesorter/"
- "view/base/web/js/sunnywalker/"
